import { useState, useEffect, useCallback } from "react";
import { useTranslation } from "react-i18next";
import { useAuth } from "../context/AuthContext";
import { seo, type SeoFiles } from "../lib/api";

export function SEO() {
  const { t } = useTranslation();
  const { user, sitePlan } = useAuth();
  const [data, setData] = useState<SeoFiles | null>(null);
  const [loading, setLoading] = useState(true);
  const [llmsText, setLlmsText] = useState("");
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");
  const [drafting, setDrafting] = useState(false);
  const [draftError, setDraftError] = useState("");

  const load = useCallback(async () => {
    if (!user) return;
    try {
      const res = await seo.get(user.siteId);
      setData(res);
      setLlmsText(res.llms.override ?? res.llms.generated);
    } catch (e) {
      setError(e instanceof Error ? e.message : t("seo.errors.load"));
    } finally {
      setLoading(false);
    }
  }, [user]);

  useEffect(() => {
    load();
  }, [load]);

  // Free-tier sites are noindex — the SEO files don't apply.
  if (sitePlan === "free") {
    return (
      <div className="page">
        <h2>{t("seo.title")}</h2>
        <section className="settings-section">
          <p>
            {t("seo.freeTier.intro")} (<code>llms.txt</code>, <code>sitemap.xml</code>, <code>robots.txt</code>) {t("seo.freeTier.availablePlans")} <strong>{t("seo.freeTier.noIndex")}</strong>{t("seo.freeTier.explanation")}
          </p>
        </section>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="page">
        <h2>{t("seo.title")}</h2>
        <p>{t("common.loading")}</p>
      </div>
    );
  }

  const usingOverride = !!data?.llms.override;

  const handleSave = async () => {
    if (!user) return;
    setSaving(true);
    setSaved(false);
    setError("");
    try {
      await seo.saveLlms(user.siteId, llmsText);
      await load();
      setSaved(true);
      setTimeout(() => setSaved(false), 3000);
    } catch (e) {
      setError(e instanceof Error ? e.message : t("seo.errors.save"));
    } finally {
      setSaving(false);
    }
  };

  const handleReset = async () => {
    if (!user || !data) return;
    setSaving(true);
    setSaved(false);
    setError("");
    try {
      await seo.saveLlms(user.siteId, null);
      setLlmsText(data.llms.generated);
      await load();
    } catch (e) {
      setError(e instanceof Error ? e.message : t("seo.errors.reset"));
    } finally {
      setSaving(false);
    }
  };

  const handleDraft = async () => {
    if (!user) return;
    setDrafting(true);
    setDraftError("");
    try {
      const res = await seo.draftLlms(user.siteId);
      setLlmsText(res.draft);
    } catch (e) {
      setDraftError(e instanceof Error ? e.message : t("seo.errors.draft"));
    } finally {
      setDrafting(false);
    }
  };

  return (
    <div className="page">
      <h2>{t("seo.title")}</h2>

      {/* llms.txt */}
      <section className="settings-section">
        <h3>
          llms.txt{" "}
          <span style={{ fontSize: "0.75rem", color: "#6b7280", fontWeight: 400 }}>
            {usingOverride ? t("seo.llms.custom") : t("seo.llms.autoGenerated")}
          </span>
        </h3>
        <p style={{ color: "#6b7280", fontSize: "0.875rem", marginTop: 0 }}>
          {t("seo.llms.descriptionP1")} (
          <a href="https://llmstxt.org" target="_blank" rel="noopener noreferrer">
            llmstxt.org
          </a>
          ){t("seo.llms.descriptionP2")}
        </p>

        <textarea
          value={llmsText}
          onChange={(e) => setLlmsText(e.target.value)}
          spellCheck={false}
          rows={18}
          style={{
            width: "100%",
            fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
            fontSize: "0.8125rem",
            lineHeight: 1.5,
            padding: "0.75rem",
            border: "1px solid #d1d5db",
            borderRadius: 6,
            resize: "vertical",
          }}
        />

        <div style={{ display: "flex", gap: "0.5rem", alignItems: "center", marginTop: "0.75rem", flexWrap: "wrap" }}>
          <button type="button" className="btn" onClick={handleDraft} disabled={drafting || saving}>
            {drafting ? t("seo.llms.writing") : t("seo.llms.writeWithAi")}
          </button>
          <button type="button" className="btn btn-primary" onClick={handleSave} disabled={saving || drafting}>
            {saving ? t("common.saving") : t("common.save")}
          </button>
          <button type="button" className="btn" onClick={handleReset} disabled={!usingOverride || saving || drafting}>
            {t("seo.llms.resetToAuto")}
          </button>
          <a href={data?.llms.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: "0.875rem" }}>
            {t("seo.viewLink")}
          </a>
          {saved && <span style={{ color: "#16a34a", fontSize: "0.875rem" }}>{t("seo.llms.saved")}</span>}
          {error && <span style={{ color: "#dc2626", fontSize: "0.875rem" }}>{error}</span>}
          {draftError && <span style={{ color: "#dc2626", fontSize: "0.875rem" }}>{draftError}</span>}
        </div>
      </section>

      {/* sitemap.xml */}
      <section className="settings-section">
        <h3>sitemap.xml</h3>
        <p style={{ color: "#6b7280", fontSize: "0.875rem", marginTop: 0 }}>
          {t("seo.sitemap.description")}
        </p>
        <div style={{ display: "flex", gap: "0.75rem", alignItems: "center" }}>
          <a href={data?.sitemap.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: "0.875rem" }}>
            {t("seo.viewLink")}
          </a>
          <span style={{ color: "#6b7280", fontSize: "0.875rem" }}>
            {t("seo.sitemap.urlCount", { count: data?.sitemap.entryCount ?? 0 })}
          </span>
        </div>
      </section>

      {/* robots.txt */}
      <section className="settings-section">
        <h3>robots.txt</h3>
        <p style={{ color: "#6b7280", fontSize: "0.875rem", marginTop: 0 }}>
          {t("seo.robots.description")}
        </p>
        <a href={data?.robots.url} target="_blank" rel="noopener noreferrer" style={{ fontSize: "0.875rem" }}>
          {t("seo.viewLink")}
        </a>
      </section>
    </div>
  );
}
