services:
  postgres:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cadmus
      POSTGRES_PASSWORD: cadmus
      POSTGRES_DB: cadmus
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
